import "./neram-home.css";

const Arrow=()=> <svg className="nr2-icon" viewBox="0 0 20 20" aria-hidden="true"><path d="M4 10h11M10.5 5.5 15 10l-4.5 4.5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>;
const Live=()=> <svg className="nr2-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M8.4 7.2a4 4 0 0 0 0 9.6M15.6 7.2a4 4 0 0 1 0 9.6M10.8 9.6a2.2 2.2 0 0 0 0 4.8M13.2 9.6a2.2 2.2 0 0 1 0 4.8" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/><circle cx="12" cy="12" r="1.3" fill="currentColor"/></svg>;
const Signal=()=> <svg className="nr2-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="4" width="8" height="16" rx="2.4" fill="none" stroke="currentColor" strokeWidth="1.5"/><circle cx="12" cy="8" r="1.6" fill="currentColor"/><circle cx="12" cy="12" r="1.6" fill="currentColor" opacity=".3"/><circle cx="12" cy="16" r="1.6" fill="currentColor" opacity=".3"/></svg>;
const Shield=()=> <svg className="nr2-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3.6 18 6v5.2c0 4.1-2.4 7.2-6 9.2-3.6-2-6-5.1-6-9.2V6l6-2.4Z" fill="none" stroke="currentColor" strokeWidth="1.5"/><path d="m9.1 12 1.9 1.9 4-4" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;

function Brand({footer=false}:{footer?:boolean}){return footer?<a className="nr2-footer-brand" href="/" aria-label="Neram home"><span className="nr2-footer-mark">N</span><strong>Neram</strong></a>:<a className="nr2-brand" href="/" aria-label="Neram home"><span className="nr2-mark">N</span><span className="nr2-brand-copy"><span className="nr2-brand-name">Neram</span><span className="nr2-brand-sub">CHENNAI EMERGENCY NETWORK</span></span></a>}

export default function Home(){return <main className="nr2">
<nav className="nr2-nav" aria-label="Primary navigation"><Brand/><div className="nr2-nav-links"><a href="/police-live" aria-current="page">Live alert</a><a href="/ambulances">Ambulances</a><a href="/map">Live map</a><a href="/police">Police console</a></div><div className="nr2-nav-side"><span className="nr2-live-pill"><i/> Training feed · 5s</span><a className="nr2-nav-cta" href="/police-live">Open console <Arrow/></a></div><details className="nr2-menu"><summary aria-label="Open navigation menu"><span/><span/><span/></summary><div className="nr2-menu-panel"><a href="/police-live">Live alert <Arrow/></a><a href="/ambulance">Ambulance mode <Arrow/></a><a href="/ambulances">Active ambulances <Arrow/></a><a href="/map">Live map <Arrow/></a><a href="/police">Police console <Arrow/></a></div></details></nav>
<section className="nr2-hero"><div><div className="nr2-kicker"><i/> Chennai · emergency response</div><h1 className="nr2-title">Give traffic police <em>time to act.</em></h1><p className="nr2-lead">Neram gives the right traffic-police unit an early warning before an active ambulance reaches their signal.</p><div className="nr2-actions"><a className="nr2-btn nr2-btn-primary" href="/police-live">Open live alert console <Arrow/></a><a className="nr2-btn nr2-btn-secondary" href="/ambulance">Open ambulance mode <Arrow/></a></div><div className="nr2-proof"><span><Shield/> Advisory only</span><span className="dot"/><span><Signal/> No signal control</span><span className="dot"/><span><Live/> Live location</span></div></div>
<div className="nr2-stage"><div className="nr2-glow"/><article className="nr2-console" aria-label="Neram live response preview"><div className="nr2-console-top"><div className="nr2-console-top-left"><div className="nr2-window-dots"><i/><i/><i/></div><span className="nr2-console-label">Neram · Chennai operations</span></div><span className="nr2-console-state"><i/> Live training</span></div><div className="nr2-map"><div className="nr2-map-grid"/><span className="nr2-map-title">ONE SIGNAL AHEAD</span><span className="nr2-map-city">ANNA SALAI / MOUNT ROAD</span><div className="nr2-road a"/><div className="nr2-road b"/><div className="nr2-road c"/><div className="nr2-road d"/><div className="nr2-route-line"/><div className="nr2-vehicle"><Live/> AMB</div><div className="nr2-signal"><Signal/> <small>GEMINI</small></div><div className="nr2-map-eta"><span>ETA TO SIGNAL</span><strong>00:38</strong><b><i/> Alert window open</b></div></div><div className="nr2-alert-strip"><div className="nr2-alert-main"><span className="nr2-alert-icon"><Signal/></span><div className="nr2-alert-copy"><span>NEXT SIGNAL</span><strong>Anna Salai · Gemini</strong></div></div><div className="nr2-alert-time"><strong>38s</strong><span>estimated arrival</span></div><span className="nr2-alert-status">Officer notified</span></div><div className="nr2-steps"><div className="nr2-step active"><b>01</b><strong>Detect</strong><span>Active emergency trip verified.</span></div><div className="nr2-step active"><b>02</b><strong>Predict</strong><span>Next relevant junction identified.</span></div><div className="nr2-step"><b>03</b><strong>Inform</strong><span>Assigned officer decides what to do.</span></div></div></article><div className="nr2-note"><div className="nr2-note-top"><span>TRAFFIC UNIT</span><b>READY</b></div><strong>Signal 04 · Gemini</strong><p>Advance warning delivered before the ambulance arrives.</p></div></div></section>
<div className="nr2-rule"/>
<section className="nr2-section"><div className="nr2-section-head"><div><div className="nr2-section-kicker">The response system</div><h2 className="nr2-section-title">The warning moves upstream.</h2></div><p className="nr2-section-copy">Neram is built around one simple idea: the officer should know before the junction becomes urgent.</p></div><div className="nr2-rail"><article className="nr2-rail-item active"><i/><b>01 · Detect</b><h3>Active trip</h3><p>Verify that the ambulance is in an active emergency journey.</p></article><article className="nr2-rail-item active"><i/><b>02 · Predict</b><h3>Next signal</h3><p>Identify the relevant junction and estimate the arrival window.</p></article><article className="nr2-rail-item alert"><i/><b>03 · Inform</b><h3>Officer action</h3><p>Send the assigned traffic unit the context needed to respond.</p></article></div></section>
<div className="nr2-rule"/>
<section className="nr2-section"><div className="nr2-split"><h2 className="nr2-quote">The ambulance should not be the first thing <span>the junction sees.</span></h2><div className="nr2-copy-stack"><div className="nr2-copy-block"><small>Early warning</small><strong>Information arrives before the emergency.</strong><p>The system moves the warning upstream instead of waiting for the ambulance to appear at the signal.</p></div><div className="nr2-copy-block"><small>Human control</small><strong>The officer remains the decision maker.</strong><p>Neram does not change traffic lights. It gives the responsible officer timely context to act.</p></div><div className="nr2-copy-block"><small>Operational clarity</small><strong>One signal. One responsible unit.</strong><p>The interface keeps attention on the next relevant junction and who owns the response.</p></div></div></div></section>
<section className="nr2-cta"><div><small>READY TO RUN THE DEMO?</small><h2>See the response before it happens.</h2><p>Explore Neram in a controlled Chennai training environment.</p></div><a className="nr2-btn nr2-btn-primary" href="/police-live">Open live alert console <Arrow/></a></section>
<footer className="nr2-footer"><Brand footer/><span>TRAINING ENVIRONMENT · CHENNAI</span></footer>
</main>}
