import "./home-motion.css";

function ArrowIcon(){return <svg viewBox="0 0 20 20" aria-hidden="true" focusable="false"><path d="M4 10h11M10.5 5.5 15 10l-4.5 4.5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function LiveIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M8.4 7.2a4 4 0 0 0 0 9.6M15.6 7.2a4 4 0 0 1 0 9.6M10.8 9.6a2.2 2.2 0 0 0 0 4.8M13.2 9.6a2.2 2.2 0 0 1 0 4.8" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/><circle cx="12" cy="12" r="1.35" fill="currentColor"/></svg>}
function MapPinIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 20s6-5.2 6-10a6 6 0 1 0-12 0c0 4.8 6 10 6 10Z" fill="none" stroke="currentColor" strokeWidth="1.6"/><circle cx="12" cy="10" r="2" fill="none" stroke="currentColor" strokeWidth="1.6"/></svg>}
function ShieldIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 3.6 18 6v5.2c0 4.1-2.4 7.2-6 9.2-3.6-2-6-5.1-6-9.2V6l6-2.4Z" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/><path d="m9.1 12 1.9 1.9 4-4" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function SignalIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="8" y="4" width="8" height="16" rx="2.4" fill="none" stroke="currentColor" strokeWidth="1.5"/><circle cx="12" cy="8" r="1.7" fill="currentColor"/><circle cx="12" cy="12" r="1.7" fill="currentColor" opacity=".34"/><circle cx="12" cy="16" r="1.7" fill="currentColor" opacity=".34"/></svg>}
function HomeBrand(){return <a className="nr-brand" href="/" aria-label="Neram home"><span className="nr-brand-mark">N</span><span className="nr-brand-name">Neram</span><span className="nr-brand-sub">CHENNAI EMERGENCY NETWORK</span></a>}
export default function Home(){return <main className="nr-home">
<nav className="nr-nav" aria-label="Primary navigation"><HomeBrand/><div className="nr-nav-links"><a href="/police-live">Live alert</a><a href="/ambulances">Ambulances</a><a href="/map">Live map</a><a href="/police">Police console</a></div><div className="nr-nav-right"><span className="nr-training"><i/> Training environment</span><a className="nr-nav-cta" href="/police-live">Open console <ArrowIcon/></a></div><details className="nr-mobile-menu"><summary aria-label="Open navigation menu"><span/><span/><span/></summary><div className="nr-mobile-panel"><div className="nr-mobile-panel-head"><HomeBrand/><span>TRAINING</span></div><a href="/police-live">Live alert <ArrowIcon/></a><a href="/ambulance">Ambulance mode <ArrowIcon/></a><a href="/map">Live map <ArrowIcon/></a><a href="/ambulances">Active ambulances <ArrowIcon/></a><a href="/police">Police console <ArrowIcon/></a></div></details></nav>
<section className="nr-hero"><div className="nr-hero-copy"><div className="nr-eyebrow"><span className="nr-live-dot"/> CHENNAI · EMERGENCY RESPONSE</div><div className="nr-live-badge"><span/> LIVE TRAINING FEED <b>5s</b></div><h1>Give traffic police <span>time to act.</span></h1><p>Neram gives the right traffic-police unit an early warning when an active ambulance is closing on their signal.</p><div className="nr-hero-actions"><a className="nr-btn-primary" href="/police-live">Open live alert console <ArrowIcon/></a><a className="nr-btn-quiet" href="/ambulance">Open ambulance mode <ArrowIcon/></a></div><div className="nr-trust"><span><ShieldIcon/> Advisory only</span><span><SignalIcon/> No signal control</span><span><LiveIcon/> Live location</span></div></div>
<div className="nr-visual-wrap"><div className="nr-orbit nr-orbit-a"/><div className="nr-orbit nr-orbit-b"/><article className="nr-live-card" aria-label="Live response preview"><header className="nr-card-header"><div><span>LIVE RESPONSE PREVIEW</span><strong>One signal ahead.</strong></div><span className="nr-status"><i/> TRAINING</span></header><div className="nr-mini-map"><div className="nr-map-grid"/><div className="nr-map-road nr-road-a"/><div className="nr-map-road nr-road-b"/><div className="nr-map-road nr-road-c"/><div className="nr-map-route"><span/></div><div className="nr-map-ambulance"><LiveIcon/><b>AMB</b></div><div className="nr-map-signal"><SignalIcon/><b>GEMINI</b></div><div className="nr-map-label nr-map-label-a">Anna Salai</div><div className="nr-map-label nr-map-label-b">Mount Road</div><div className="nr-map-eta"><small>ETA TO SIGNAL</small><strong>00:38</strong><span>Alert window open</span></div></div><div className="nr-card-steps"><div className="nr-step is-done"><span>01</span><div><small>ACTIVE TRIP</small><strong>AMB-DEMO-01</strong><p>Live location sharing</p></div><i/></div><div className="nr-step is-alert"><span>02</span><div><small>NEXT SIGNAL</small><strong>Anna Salai · Gemini</strong><p>38s estimated arrival</p></div><i/></div><div className="nr-step"><span>03</span><div><small>OFFICER</small><strong>Assigned unit notified</strong><p>Officer decides how to respond</p></div><i/></div></div><footer><span className="nr-footer-pulse"/> EARLY WARNING · NOT AUTOMATED CONTROL</footer></article></div></section>
<section className="nr-metrics" aria-label="Neram response flow"><div><span>01</span><strong>Detect</strong><p>Verify the active emergency trip.</p></div><div><span>02</span><strong>Predict</strong><p>Identify the next relevant signal.</p></div><div><span>03</span><strong>Inform</strong><p>Give the assigned officer time to act.</p></div><div className="nr-metric-note"><span>BUILT FOR CLARITY</span><strong>Information arrives before the emergency does.</strong></div></section>
<section className="nr-story"><div className="nr-story-kicker">WHY NERAM EXISTS</div><div className="nr-story-grid"><h2>The ambulance should not be the first thing the junction sees.</h2><div><p>Neram moves the warning upstream. The ambulance shares its live position, the system identifies the next relevant signal, and the officer gets the information before the emergency reaches the junction.</p><a href="/police-live">See the response flow <ArrowIcon/></a></div></div></section>
<section className="nr-flow"><div className="nr-flow-intro"><span>THE RESPONSE LOOP</span><h2>One signal. Three decisions.</h2><p>Every screen is designed around the same question: what does the officer need to know right now?</p></div><div className="nr-flow-list"><div><b>01</b><strong>Active trip</strong><span>Confirm the ambulance is moving under an active emergency trip.</span></div><div><b>02</b><strong>Next signal</strong><span>Surface the relevant junction before it becomes urgent.</span></div><div><b>03</b><strong>Officer action</strong><span>Give the assigned unit context, not automated control.</span></div></div></section>
<section className="nr-cta"><div><span>READY TO RUN THE DEMO?</span><h2>Start with the live alert console.</h2><p>Everything here runs in a controlled training environment.</p></div><a className="nr-btn-primary" href="/police-live">Open live alert console <ArrowIcon/></a></section><footer className="nr-footer"><HomeBrand/><span>TRAINING ENVIRONMENT · CHENNAI</span></footer>
</main>}
