"use client";

import "../premium-ops.css";
import "../interface-polish.css";
import "../install-prompt.css";
import "../ops-nav.css";
import "../ambulance-field.css";
import InstallPrompt from "../InstallPrompt";
import OpsNav from "../OpsNav";
import { getSupabaseBrowserClient } from "../../lib/supabase/browser";
import { useEffect, useRef, useState } from "react";

const DEMO_POINTS=[{latitude:13.0458,longitude:80.2079},{latitude:13.0466,longitude:80.2087},{latitude:13.0472,longitude:80.2094},{latitude:13.0479,longitude:80.2103},{latitude:13.0486,longitude:80.211},{latitude:13.0494,longitude:80.2118},{latitude:13.0503,longitude:80.2127},{latitude:13.0511,longitude:80.2134},{latitude:13.052,longitude:80.2145},{latitude:13.0527,longitude:80.2153}];
type Decision={shouldAlert:boolean;reason:string;signal:{id:string;name:string}|null;distanceToSignalMeters:number|null;estimatedEtaSeconds:number|null};type GpsState="simulation"|"device"|"denied"|"unavailable";
export default function AmbulancePage(){
  const [active,setActive]=useState(false);const [online,setOnline]=useState(true);const [seconds,setSeconds]=useState(0);const [shared,setShared]=useState(false);const [pointIndex,setPointIndex]=useState(0);const [decision,setDecision]=useState<Decision|null>(null);const [lastUpdate,setLastUpdate]=useState<string|null>(null);const [sending,setSending]=useState(false);const [gpsState,setGpsState]=useState<GpsState>("simulation");const [accuracyMeters,setAccuracyMeters]=useState<number|null>(null);const [gpsError,setGpsError]=useState<string|null>(null);const [demo,setDemo]=useState(true);const watchId=useRef<number|null>(null);
  useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener("online",sync);window.addEventListener("offline",sync);const access=localStorage.getItem("neram_access_mode");setDemo(access!=='verified');return()=>{window.removeEventListener("online",sync);window.removeEventListener("offline",sync)}},[]);
  useEffect(()=>{if(!active)return;const t=window.setInterval(()=>setSeconds(v=>v+1),1000);return()=>window.clearInterval(t)},[active]);
  useEffect(()=>{if(!active||!shared||gpsState!=="simulation")return;const t=window.setInterval(()=>setPointIndex(v=>v>=DEMO_POINTS.length-1?0:v+1),2200);return()=>window.clearInterval(t)},[active,shared,gpsState]);
  const sendUpdate=async(point:{latitude:number;longitude:number},speedMps:number)=>{const headers=new Headers({"content-type":"application/json"});let url="/api/ambulance/update";if(demo){url+="?mode=demo"}else{const{data:{session}}=await getSupabaseBrowserClient().auth.getSession();if(!session?.access_token)throw new Error("Operator session expired. Please sign in again.");headers.set("authorization",`Bearer ${session.access_token}`)}const response=await fetch(url,{method:"POST",headers,body:JSON.stringify({...point,speedMps,gpsQuality:"good"})});if(!response.ok){const data=(await response.json().catch(()=>null))as{error?:string}|null;throw new Error(data?.error||"GPS update rejected")}return response.json()as Promise<{decision:Decision|null}>};
  useEffect(()=>{if(!active||!shared||gpsState!=="device")return;if(!navigator.geolocation){setGpsState("unavailable");setGpsError("This device does not expose browser location services.");return}const id=navigator.geolocation.watchPosition(position=>{const point={latitude:position.coords.latitude,longitude:position.coords.longitude};setAccuracyMeters(Number.isFinite(position.coords.accuracy)?position.coords.accuracy:null);setGpsError(null);setSending(true);sendUpdate(point,Number.isFinite(position.coords.speed)&&position.coords.speed!==null?Math.max(0,position.coords.speed):13.9).then(d=>{setDecision(d.decision);setLastUpdate(new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"}))}).catch(error=>setGpsError(error instanceof Error?error.message:"Neram could not process the latest GPS update.")).finally(()=>setSending(false))},error=>{if(error.code===error.PERMISSION_DENIED){setGpsState("denied");setGpsError("Location permission was denied. Simulation remains available.")}else setGpsError("Unable to obtain a fresh GPS position.")},{enableHighAccuracy:true,maximumAge:5000,timeout:10000});watchId.current=id;return()=>{navigator.geolocation.clearWatch(id);watchId.current=null}},[active,shared,gpsState,demo]);
  useEffect(()=>{if(!active||!shared||gpsState!=="simulation")return;const point=DEMO_POINTS[pointIndex];setSending(true);sendUpdate(point,13.9).then(d=>{setDecision(d.decision);setLastUpdate(new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"}))}).catch(error=>setGpsError(error instanceof Error?error.message:"Update failed")).finally(()=>setSending(false))},[active,shared,pointIndex,gpsState,demo]);
  const resetTrip=async()=>{if(watchId.current!==null&&navigator.geolocation){navigator.geolocation.clearWatch(watchId.current);watchId.current=null}if(!demo){try{const{data:{session}}=await getSupabaseBrowserClient().auth.getSession();if(session?.access_token)await fetch("/api/ambulance/trip",{method:"PATCH",headers:{authorization:`Bearer ${session.access_token}`}})}catch(error){setGpsError(error instanceof Error?error.message:"Unable to end the verified trip.");return}}setActive(false);setShared(false);setSeconds(0);setPointIndex(0);setDecision(null);setLastUpdate(null);setGpsState("simulation");setAccuracyMeters(null);setGpsError(null)};
  const startTrip=async()=>{if(!online){setGpsError("No internet connection. Neram cannot send live ambulance updates right now.");return}setGpsError(null);if(!demo){try{const{data:{session}}=await getSupabaseBrowserClient().auth.getSession();if(!session?.access_token)throw new Error("Operator session expired. Please sign in again.");const response=await fetch("/api/ambulance/trip",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`},body:JSON.stringify({destinationName:(document.querySelector<HTMLInputElement>(".ambulance-fields input")?.value||"").trim()})});const data=(await response.json().catch(()=>null))as{error?:string}|null;if(!response.ok)throw new Error(data?.error||"Unable to start verified emergency trip")}catch(error){setGpsError(error instanceof Error?error.message:"Unable to start the verified trip.");return}}setActive(true)};
  const enableDeviceGps=()=>{if(!online){setGpsError("Reconnect to the internet before enabling live GPS updates.");return}setGpsError(null);setGpsState("device");setShared(true)};
  return <main className="ambulance-shell"><OpsNav section="AMBULANCE MODE" status={!online?"OFFLINE":active?(demo?"TRAINING":"LIVE"):(demo?"TRAINING":"READY")}/>{!online&&<div className="ambulance-connection-loss" role="alert"><span>!</span><div><strong>You're offline</strong><p>Live ambulance updates are paused until the connection returns.</p></div></div>}
    <section className="ambulance-card ambulance-hero"><div className="map-overline">{demo?"DEMO AMBULANCE · TRAINING":"VERIFIED AMBULANCE · LIVE"}</div><h1>{active?"Location sharing is on.":"Start an emergency trip."}</h1><p>{active?"Neram is preparing advance information for traffic police along your route.":"When activated, Neram shares your live position during this emergency trip. It never controls traffic signals."}</p><div className="ambulance-meta-grid"><div><span>AMBULANCE</span><strong>{demo?"AMB-DEMO-01":"VERIFIED UNIT"}</strong></div><div><span>TRIP TIME</span><strong>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</strong></div></div><button type="button" disabled={!active&&!online} className={active?"ambulance-stop":"ambulance-start"} onClick={()=>void(active?resetTrip():startTrip())}><span>{active?"End emergency trip":online?"Start emergency trip":"Waiting for connection"}</span><span>{active?"■":"→"}</span></button>
      {active&&<div className="ambulance-sharing" role="status"><span className={`sharing-indicator ${shared?"is-shared":""}`}/><div><strong>{shared?(gpsState==="device"?"Device GPS active":"Simulation GPS active"):"Location not shared"}</strong><p>{!shared?"Enable training location sharing to exercise the alert pipeline.":gpsState==="device"?`${accuracyMeters?`Accuracy ±${Math.round(accuracyMeters)}m`:"Waiting for GPS accuracy"} · ${sending?"Sending update…":lastUpdate?`Last update ${lastUpdate}`:"Waiting for first GPS update."}`:sending?"Sending simulated GPS update…":lastUpdate?`Last update ${lastUpdate}`:"Waiting for first simulated GPS update."}</p></div>{!shared?<button type="button" onClick={()=>setShared(true)}>Simulate GPS</button>:gpsState==="device"?<button type="button" onClick={()=>{setGpsState("simulation");setAccuracyMeters(null);setGpsError(null)}}>Simulation</button>:<button type="button" onClick={enableDeviceGps}>Use device GPS</button>}</div>}{gpsError&&<p className="ambulance-note" role="alert">{gpsError}</p>}{decision?.shouldAlert&&<div className="ambulance-alert-preview" role="status"><div><span>ALERT WINDOW OPEN</span><strong>{decision.signal?.name}</strong></div><div><strong>{decision.estimatedEtaSeconds??"—"}s</strong><small>ETA</small></div></div>}
    </section><section className="ambulance-card"><div className="map-overline">TRIP DETAILS</div><div className="ambulance-fields"><label>Destination <input placeholder="Hospital or destination…"/></label><label>Priority <select defaultValue="emergency"><option value="emergency">Emergency</option><option value="critical">Critical</option></select></label></div><p className="ambulance-note">{demo?"Training mode. Device GPS can be exercised in-browser; no production police network is used.":"Verified operational mode. Trip and GPS updates are stored under the authenticated ambulance account."}</p></section><InstallPrompt/>
  </main>;
}
