"use client";

import "../premium-ops.css";
import "../interface-polish.css";
import "../install-prompt.css";
import "../ops-nav.css";
import InstallPrompt from "../InstallPrompt";
import OpsNav from "../OpsNav";
import { useEffect, useRef, useState } from "react";

const DEMO_POINTS=[{latitude:13.0458,longitude:80.2079},{latitude:13.0466,longitude:80.2087},{latitude:13.0472,longitude:80.2094},{latitude:13.0479,longitude:80.2103},{latitude:13.0486,longitude:80.211},{latitude:13.0494,longitude:80.2118},{latitude:13.0503,longitude:80.2127},{latitude:13.0511,longitude:80.2134},{latitude:13.052,longitude:80.2145},{latitude:13.0527,longitude:80.2153}];
type Decision={shouldAlert:boolean;reason:string;signal:{id:string;name:string}|null;distanceToSignalMeters:number|null;estimatedEtaSeconds:number|null};type GpsState="simulation"|"device"|"denied"|"unavailable";
export default function AmbulancePage(){
  const [active,setActive]=useState(false);const [online,setOnline]=useState(true);const [seconds,setSeconds]=useState(0);const [shared,setShared]=useState(false);const [pointIndex,setPointIndex]=useState(0);const [decision,setDecision]=useState<Decision|null>(null);const [lastUpdate,setLastUpdate]=useState<string|null>(null);const [sending,setSending]=useState(false);const [gpsState,setGpsState]=useState<GpsState>("simulation");const [accuracyMeters,setAccuracyMeters]=useState<number|null>(null);const [gpsError,setGpsError]=useState<string|null>(null);const watchId=useRef<number|null>(null);
  useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener("online",sync);window.addEventListener("offline",sync);return()=>{window.removeEventListener("online",sync);window.removeEventListener("offline",sync)}},[]);
  useEffect(()=>{if(!active)return;const t=window.setInterval(()=>setSeconds(v=>v+1),1000);return()=>window.clearInterval(t)},[active]);
  useEffect(()=>{if(!active||!shared||gpsState!=="simulation")return;const t=window.setInterval(()=>setPointIndex(v=>v>=DEMO_POINTS.length-1?0:v+1),2200);return()=>window.clearInterval(t)},[active,shared,gpsState]);
  useEffect(()=>{if(!active||!shared||gpsState!=="device")return;if(!navigator.geolocation){setGpsState("unavailable");setGpsError("This device does not expose browser location services.");return}const id=navigator.geolocation.watchPosition(position=>{const point={latitude:position.coords.latitude,longitude:position.coords.longitude};setAccuracyMeters(Number.isFinite(position.coords.accuracy)?position.coords.accuracy:null);setGpsError(null);setSending(true);fetch("/api/ambulance/update",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...point,speedMps:Number.isFinite(position.coords.speed)&&position.coords.speed!==null?Math.max(0,position.coords.speed):13.9,gpsQuality:position.coords.accuracy<=30?"good":"degraded"})}).then(async r=>{if(!r.ok)throw new Error("GPS update rejected");return r.json() as Promise<{decision:Decision}>}).then(d=>{setDecision(d.decision);setLastUpdate(new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"}))}).catch(()=>setGpsError("Neram could not process the latest GPS update.")).finally(()=>setSending(false))},error=>{if(error.code===error.PERMISSION_DENIED){setGpsState("denied");setGpsError("Location permission was denied. Simulation remains available.")}else setGpsError("Unable to obtain a fresh GPS position.")},{enableHighAccuracy:true,maximumAge:5000,timeout:10000});watchId.current=id;return()=>{navigator.geolocation.clearWatch(id);watchId.current=null}},[active,shared,gpsState]);
  useEffect(()=>{if(!active||!shared||gpsState!=="simulation")return;const point=DEMO_POINTS[pointIndex];setSending(true);fetch("/api/ambulance/update",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...point,speedMps:13.9,gpsQuality:"good"})}).then(async r=>{if(!r.ok)throw new Error("Update failed");return r.json() as Promise<{decision:Decision}>}).then(d=>{setDecision(d.decision);setLastUpdate(new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"}))}).catch(()=>setLastUpdate(null)).finally(()=>setSending(false))},[active,shared,pointIndex,gpsState]);
  const resetTrip=()=>{if(watchId.current!==null&&navigator.geolocation){navigator.geolocation.clearWatch(watchId.current);watchId.current=null}setActive(false);setShared(false);setSeconds(0);setPointIndex(0);setDecision(null);setLastUpdate(null);setGpsState("simulation");setAccuracyMeters(null);setGpsError(null)};
  const startTrip=()=>{if(!online){setGpsError("No internet connection. Neram cannot send live ambulance updates right now.");return}setGpsError(null);setActive(true)};const enableDeviceGps=()=>{if(!online){setGpsError("Reconnect to the internet before enabling live GPS updates.");return}setGpsError(null);setGpsState("device");setShared(true)};
  return <main className="ambulance-shell"><OpsNav section="AMBULANCE MODE" status={!online?"OFFLINE":active?"EMERGENCY ACTIVE":"TRAINING"}/>{!online&&<div className="ambulance-connection-loss" role="alert"><span>!</span><div><strong>You're offline</strong><p>Live ambulance updates are paused until the connection returns.</p></div></div>}
    <section className="ambulance-card ambulance-hero"><div className="map-overline">AUTHORIZED AMBULANCE · TRAINING</div><h1>{active?"Location sharing is on.":"Start an emergency trip."}</h1><p>{active?"Neram is preparing advance information for traffic police along your route.":"When activated, Neram shares your live position during this emergency trip. It never controls traffic signals."}</p><div className="ambulance-meta-grid"><div><span>AMBULANCE</span><strong>AMB-DEMO-01</strong></div><div><span>TRIP TIME</span><strong>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</strong></div></div><button type="button" disabled={!active&&!online} className={active?"ambulance-stop":"ambulance-start"} onClick={()=>active?resetTrip():startTrip()}><span>{active?"End emergency trip":online?"Start emergency trip":"Waiting for connection"}</span><span>{active?"■":"→"}</span></button>
      {active&&<div className="ambulance-sharing" role="status"><span className={`sharing-indicator ${shared?"is-shared":""}`}/><div><strong>{shared?(gpsState==="device"?"Device GPS active":"Simulation GPS active"):"Location not shared"}</strong><p>{!shared?"Enable training location sharing to exercise the alert pipeline.":gpsState==="device"?`${accuracyMeters?`Accuracy ±${Math.round(accuracyMeters)}m`:"Waiting for GPS accuracy"} · ${sending?"Sending update…":lastUpdate?`Last update ${lastUpdate}`:"Waiting for first GPS update."}`:sending?"Sending simulated GPS update…":lastUpdate?`Last update ${lastUpdate}`:"Waiting for first simulated GPS update."}</p></div>{!shared?<button type="button" onClick={()=>setShared(true)}>Simulate GPS</button>:gpsState==="device"?<button type="button" onClick={()=>{setGpsState("simulation");setAccuracyMeters(null);setGpsError(null)}}>Simulation</button>:<button type="button" onClick={enableDeviceGps}>Use device GPS</button>}</div>}{gpsError&&<p className="ambulance-note" role="alert">{gpsError}</p>}{decision?.shouldAlert&&<div className="ambulance-alert-preview" role="status"><div><span>ALERT WINDOW OPEN</span><strong>{decision.signal?.name}</strong></div><div><strong>{decision.estimatedEtaSeconds??"—"}s</strong><small>ETA</small></div></div>}
    </section><section className="ambulance-card"><div className="map-overline">TRIP DETAILS</div><div className="ambulance-fields"><label>Destination <input placeholder="Hospital or destination…"/></label><label>Priority <select defaultValue="emergency"><option value="emergency">Emergency</option><option value="critical">Critical</option></select></label></div><p className="ambulance-note">Training mode. Device GPS can be exercised in-browser, but no live police network or Supabase persistence is enabled yet.</p></section><InstallPrompt/>
  </main>;
}
