"use client";

import "../premium-ops.css";
import "../interface-polish.css";
import "../ops-nav.css";
import "./police-elite.css";
import { useState } from "react";
import OpsNav from "../OpsNav";

function ArrowIcon(){return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4 10h11M10.5 5.5 15 10l-4.5 4.5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function SignalIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="4" width="8" height="16" rx="2.4" fill="none" stroke="currentColor" strokeWidth="1.5"/><circle cx="12" cy="8" r="1.7" fill="currentColor"/><circle cx="12" cy="12" r="1.7" fill="currentColor" opacity=".34"/><circle cx="12" cy="16" r="1.7" fill="currentColor" opacity=".34"/></svg>}

export default function PoliceDashboard(){
  const [ack,setAck]=useState(false);const [cleared,setCleared]=useState(false);const status=cleared?"CLEARED":ack?"ACKNOWLEDGED":"ACTION NEEDED";
  return <main className="ops-shell police-page"><OpsNav section="POLICE SIGNAL WATCH" status={status}/><div className="ops-content police-content">
    <section className="ops-heading police-heading"><div><div className="label">TRAFFIC POLICE · TRAINING CONSOLE</div><h1>Signal watch</h1><p>Advance information for authorized traffic personnel.</p></div><span className={`ops-status ${cleared?"ok":ack?"ack":"urgent"}`}><i/> {status}</span></section>
    {!cleared?<section className={`priority-alert police-priority ${ack?"acknowledged":""}`}><div className="priority-icon">!</div><div className="priority-copy"><div className="priority-label">{ack?"AMBULANCE MONITORING":"AMBULANCE APPROACHING"}</div><h2>AMB-DEMO-01</h2><p>Approaching <strong>Demo Signal A</strong> from the west</p></div><div className="priority-eta"><strong>{ack?"18":"42"}</strong><span>seconds</span></div></section>:<section className="cleared-banner police-cleared"><span>✓</span><div><strong>Ambulance cleared the signal</strong><p>The training alert is closed.</p></div></section>}
    <div className="ops-grid police-grid"><section className="ops-panel police-signal-panel"><div className="panel-head"><div><div className="label">YOUR ASSIGNED SIGNAL</div><h2>Demo Signal A</h2><p>Simulation corridor</p></div><span className="assigned">ASSIGNED</span></div><div className="intersection police-intersection"><div className="intersection-glow"/><div className="road road-h"/><div className="road road-v"/><div className="road road-h road-soft"/><div className="road road-v road-soft"/><div className="signal-light"><i/><i/><i/></div><div className="ambulance-token"><span>AMB</span></div><div className="route-trail"/><div className="map-corner north">N</div><div className="intersection-tag"><SignalIcon/><span>DEMO SIGNAL A</span></div></div><div className="mini-stats police-stats"><div><span>Approach</span><strong>West → East</strong></div><div><span>Distance</span><strong>~310 m</strong></div><div><span>GPS quality</span><strong className="good">Good</strong></div></div></section>
      <aside className="ops-panel action-panel police-action-panel"><div className="label">OFFICER ACTION</div><div className="action-state">{cleared?"Closed":ack?"Monitoring":"Prepare"}</div><h2>{cleared?"All clear":ack?"Keep watch":"Prepare ahead"}</h2><p>{cleared?"No further action is required for this training event.":"Use this alert as advance information and follow existing traffic-control procedure."}</p>{!cleared&&!ack&&<button type="button" className="primary-action police-primary-action" onClick={()=>setAck(true)}><span>Acknowledge alert</span><ArrowIcon/></button>}{ack&&!cleared&&<button type="button" className="secondary-action police-secondary-action" onClick={()=>setCleared(true)}><span>Mark signal cleared</span><span>✓</span></button>}{cleared&&<a className="secondary-action police-secondary-action" href="/police-live"><span>Return to live alerts</span><ArrowIcon/></a>}<div className="action-note"><span>i</span><span>Neram does not control traffic signals. It provides advance information only.</span></div></aside></div>
    <section className="event-panel police-event-panel"><div className="panel-head"><div><div className="label">EVENT TIMELINE</div><h2>Response history</h2></div><span className="muted">Training event</span></div><div className="timeline police-timeline"><div className="event active"><span/><div><strong>Approaching signal</strong><p>ETA window opened</p></div><time>Now</time></div><div className={`event ${ack?"active":""}`}><span/><div><strong>Officer acknowledgement</strong><p>{ack?"Alert acknowledged":"Waiting for acknowledgement"}</p></div><time>{ack?"Now":"—"}</time></div><div className={`event ${cleared?"active":""}`}><span/><div><strong>Signal cleared</strong><p>{cleared?"Training trip completed":"Pending"}</p></div><time>{cleared?"Now":"—"}</time></div></div></section>
    <footer className="ops-footer police-footer"><span>TRAINING ENVIRONMENT · ADVISORY ONLY</span><span>No automated signal control</span></footer>
  </div></main>
}
