"use client";

import "../premium-ops.css";
import "../interface-polish.css";
import { useEffect, useRef, useState } from "react";

type Alert = { id:string; ambulanceId:string; signalName:string; status:string; etaSeconds:number; distanceMeters:number; approach:string; gpsQuality:string };

export default function PoliceLivePage(){
  const [alert,setAlert]=useState<Alert|null>(null); const [updatedAt,setUpdatedAt]=useState<string|null>(null); const [acknowledged,setAcknowledged]=useState(false); const [feedError,setFeedError]=useState(false); const [notifications,setNotifications]=useState<NotificationPermission|"unsupported">("default"); const previousAlertId=useRef<string|null>(null);
  const enableNotifications=async()=>{if(!("Notification" in window))return setNotifications("unsupported");setNotifications(await Notification.requestPermission())};
  useEffect(()=>{if("Notification" in window)setNotifications(Notification.permission);const load=async()=>{try{const response=await fetch("/api/police/alerts",{cache:"no-store"});if(!response.ok)throw new Error("feed unavailable");const data=(await response.json()) as {alerts?:Alert[];generatedAt?:string};const next=data.alerts?.[0]??null;setAlert(next);setUpdatedAt(data.generatedAt??null);setFeedError(false);if(next&&previousAlertId.current&&previousAlertId.current!==next.id&&"Notification" in window&&Notification.permission==="granted")new Notification("Neram: ambulance approaching",{body:`${next.ambulanceId} is approaching ${next.signalName}. ETA ${next.etaSeconds}s.`});previousAlertId.current=next?.id??null}catch{setFeedError(true)}};void load();const timer=window.setInterval(load,5000);return()=>window.clearInterval(timer)},[]);
  const ageSeconds=updatedAt?Math.max(0,Math.floor((Date.now()-new Date(updatedAt).getTime())/1000)):null; const fresh=ageSeconds!==null&&ageSeconds<=8; const feedStatus=feedError?"Alert feed unavailable":!fresh?"Alert feed is stale":"Alert feed is connected"; const urgency=alert?(alert.etaSeconds<=15?"critical":alert.etaSeconds<=45?"near":"approaching"):"approaching";
  return <main className="live-shell"><div className="live-container"><header className="live-header"><a className="live-brand" href="/" aria-label="Back to Neram home"><span className="brand-mark">N</span><span><strong>Neram</strong><small>POLICE SIGNAL WATCH</small></span></a><div className="live-header-actions"><button type="button" className="notification-button" onClick={enableNotifications} disabled={notifications==="granted"||notifications==="unsupported"}>{notifications==="granted"?"Alerts on":notifications==="denied"?"Alerts blocked":"Enable alerts"}</button><div className={`feed-state ${feedError||!fresh?"warning":"ok"}`} aria-live="polite"><i/>{feedError?"Feed degraded":!fresh?"Stale feed":"Connected · training"}</div></div></header>
    <p className="sr-only" aria-live="polite">{feedStatus}{updatedAt?`. Last refresh ${ageSeconds} seconds ago.`:"."}</p>
    {!alert?<section className={`live-empty ${feedError?"degraded":""}`} aria-live="polite"><span className="live-empty-icon">{feedError?"!":"✓"}</span><div><strong>{feedError?"Alert feed unavailable":"No active ambulance alerts"}</strong><p>{feedError?"Neram will retry automatically.":"Neram is monitoring your assigned signals."}</p></div></section>:<><section className={`live-alert-card urgency-${urgency}`}><div className="live-alert-label">{urgency==="critical"?"AMBULANCE AT SIGNAL":"AMBULANCE APPROACHING"}</div><div className="live-alert-main"><div><h1>{alert.signalName}</h1><p>{alert.ambulanceId} · approaching {alert.approach}</p></div><div className="live-eta"><strong>{alert.etaSeconds}s</strong><span>estimated arrival</span></div></div></section><section className="live-metrics"><div><span>Distance ahead</span><strong>{alert.distanceMeters} m</strong></div><div><span>Approach</span><strong>{alert.approach}</strong></div><div><span>GPS quality</span><strong>{alert.gpsQuality.toUpperCase()}</strong></div></section><section className={`live-response-card ${acknowledged?"is-acknowledged":""}`}><div className="live-response-copy"><div className="live-section-label">OFFICER RESPONSE</div><h2>{acknowledged?"Monitoring":"Action needed"}</h2><p>Use this information and follow existing traffic-control procedure.</p></div><button type="button" className={`live-ack ${acknowledged?"done":""}`} onClick={()=>setAcknowledged(value=>!value)} aria-pressed={acknowledged}>{acknowledged?"Acknowledged":"Acknowledge alert"}</button><div className="live-disclaimer">Neram never changes traffic signals automatically.</div></section></>}
    <footer className="live-footer"><span>Training event feed · refresh every 5s</span><span>{updatedAt?`Last refresh ${new Date(updatedAt).toLocaleTimeString()} · ${ageSeconds}s ago`:"Waiting for feed"}</span></footer></div></main>
}
